---
title: "validatedDataPrep"
output: html_document
date: "2024-12-16"
---

```{r setup} 
knitr::opts_chunk$set(echo = FALSE) #for all chunks we dont want to see code in markdown output
```


```{r imports} 
#updated 4/1

if (!require("pacman")) 
  install.packages("pacman") #this basically makes it so we dont have to do library(package) for each package, and also automatically downloads the packages if you dont already have them downloaded from CRAN (Comprehensive R Archive Network)

pacman::p_load(
  here, #import data
  janitor, #cleaning header names into R readable headers if not readable already
  tidyverse, #ggplot, dplyr, readr etc.
  datawizard, #joining all the weather in one line of code
  timetk, #for condensing time periods for rainfall
  zoo, #for roll apply function
  IETD #library for calculating rainfall intensities
  
)

```

```{r read in data}

valData <- read_csv(here("rockfall_mine7_min_binary_validated.csv"))
valData <- data.frame("date" = valData$Date, "timeOfInitiation" = valData$`Time of Initiation`) #re-format a bit

#MINE8
jan <- read_csv(here('data/jan2022.csv'))
feb <- read_csv(here('data/feb2022.csv'))
mar <- read_csv('data/mar2022.csv') 
apr <- read_csv('data/apr2022.csv')
teck <- read_csv('data/teckWeather.csv')
colnames(teck) <- teck[2,]
teck <-(teck[c(636:2483),])
teck <- clean_names(teck)
noView <- read_csv(here("data/timesUnavailable.csv"))
```


``` {r clean up weather data}

mine8Weather <- data_merge(list(jun,july, aug, sept), join = "bind") #essentially a full join of multiple data frames

mine8Weather <- mine8Weather[c(28782:149739),] #constrain time to deployment range at mine 8

mine8Weather <- mine8Weather |>
  mutate('datetime' = as_datetime(timestamp)) |>
  mutate('time' = ((timestamp) - (timestamp[1]))/60) |> 
  # mutate('rainmm' = (Rain.Meter.inst-lag(Rain.Meter.inst))*0.1) |> #instantaneous rain values
  # mutate('rainmm' = replace_na(rainmm, 0)) |> # handle NA values in rainM so cumulative sum works
  mutate('irradiance' = ((`Solar Irradiance.inst`)/(56.62*(1+0.0006*(`Outdoor Temp.avg`-32)*5/9)))) |>
  mutate('irradiance' = ifelse(irradiance< 0, 0, irradiance)) |> 
  mutate('tempC' = (`Outdoor Temp.avg`-32)*5/9) |>
  # mutate('sumrain24' = rollapply(rainmm, width = 1440, FUN = sum, fill = 0, align = 'left')) |> #remove for mine8 since we need to recalc below
  # mutate('rainmmCumu' = cumsum(rainmm)) |> #rolling sum
  mutate('windMS' = `mTK Wind Speed.inst`/2.2369) |>
  group_by(datetime, 
           tempC,
           time,
           # sumrain24,
           # rainmm, 
           windMS, 
           irradiance, 
           # rainmmCumu
           ) |>
  # filter(rainmm >= 0 ) |> #remove rainfall values that are negative 
  dplyr::summarise(.groups = 'drop')

mine8Weather <- condense_period(mine8Weather, .period = 'hour', .date_var = datetime,  .side = c('start'))

# Create the data frame
df <- data.frame(datetime = as.POSIXct(morenci$Recorded, format = "%m/%d/%Y %H:%M"), 
                 sum12 = morenci$WCWS1_Rainfall_Past12HrSum*2.54)

# Calculate the instantaneous hourly values
df <- df |>
  mutate(intRain = (sum12/144)) |>  # 144 intervals in 12 hours
  filter(intRain >= 0) |> 
  mutate(basicTest = rollapply(intRain, width = 144, FUN = sum, fill = 0, align = 'right', partial = FALSE)) |>
  mutate('diffTest' = rollapply(sum12, width = 144, FUN = diff, fill = 0, align = 'right', partial = FALSE)) |> 
  mutate('sumTest' = rollapply(diffTest, width = 144, FUN = sum, fill = 0, align = 'left', partial = FALSE)) 

#replace negatives with zeros
df[, 3:ncol(df)] <- lapply(df[, 3:ncol(df)], function(x) ifelse(x < 0, 0, x))

#Replace NAs with zeros
df <- df %>%
  mutate(across(-datetime, ~ifelse(is.na(.), 0, .)))


#-----------------------------------
#CAN'T RECALL WHAT THIS PLOT IS FOR....
#-----------------------------------
ggplot(df) +
  geom_line(aes(sumTest[,1], sum12)) + 
  geom_line(aes(basicTest, sum12), color = 'red')
#confirm that the values are similar


#vector of hourly rain values from morenci
diffTest <- data.frame(datetime = df$datetime, instRain = df$diffTest[,143])
diffTest_hourly <- diffTest %>%
  group_by(datetime_hour = floor_date(datetime, unit = "hour")) %>%
  summarize(sum_instRain = sum(instRain, na.rm = TRUE))

mine8Weather <- mine8Weather |> 
  mutate('rainmm' = (diffTest_hourly$sum_instRain*10), 
         # 'sumrain24'= rollapply(as.numeric(diffTest_hourly$sum_instRain*10), width = 24, FUN = sum, fill = 0, align = 'left', partial = TRUE),
         # 'sumrain6'= rollapply(as.numeric(diffTest_hourly$sum_instRain*10), width = 6, FUN = sum, fill = 0, align = 'left', partial = TRUE),
         'cumuRain' = cumsum(rainmm))


```

```{r calculate rainfall intensities}


#Calculate rain intensities MINE 8
 
test <- mine8Weather |> 
  reframe(Date = datetime, Rainfall.depth = rainmm) |> 
  data.frame()

# Convert datetime to character string
cva <- CVA(test)
plot <- cva$Figure
#found that IETD is 1.7 hours
#thus define rainfall events
plot <- plot + 
  labs(
    title = "Inter Event Time Definition Delineation",
    x = "Inter Event Time Definition (IETD)",
    y = "Coefficient of Variation (CVA)"
  )

result <- IETD::drawre(test, 1.7, 1) #find events that are at least 1.7 hours apart and rain more than 1mm
ggsave(file=here("figures/mine8IETD.png"), plot=plot, width=5, height=5)


#assign intensity to each time period
get_intensity <- function(dt) {
  within_interval <- dt >= result$Rainfall_Characteristics$Starting & dt <= result$Rainfall_Characteristics$End
  if (any(within_interval)) {
    return(result$Rainfall_Characteristics$Intensity[which(within_interval)[1]])
  } else {
    return(0)
  }
}

mine8Weather <- mine8Weather |>
  mutate('intensity' = sapply(datetime, get_intensity))

#plot precipitation events

PI8 <- ggplot(result$Rainfall_Characteristics) + 
  geom_col(aes(Starting, Intensity)) + 
  labs(x = '', 
       y = 'Intensity (mm/hr)', 
       title = 'Mine 8: Precipitation Events by Intensity') + 
  scale_y_continuous(expand = c(0,0), limits = c(0,8)) + #CAN DO THIS FOR ABOVE WEATHER TO MAKE THEM LOOK NICER
  scale_x_datetime(expand = c(0, 0)) +
  theme_bw() + 
  theme(
    axis.title.x = element_blank(), 
    axis.text.y = element_text(size = 14), 
    axis.title.y = element_text(size = 14), 
    axis.text.x = element_text(size = 14), 
    plot.title = element_text(size = 18), 
    aspect.ratio = 0.618
  )

PI8
ggsave(file="PI8.svg", plot=PI8, width=8, height=5)


PD8 <- ggplot(result$Rainfall_Characteristics) + 
  # geom_col(aes(Starting, Duration)) +
  geom_rect(aes(xmin = Starting,
                xmax = End,
                ymin = 0,
                ymax = Inf),
            fill = 'pink',
            show.legend = FALSE,
            alpha = 1) +
  labs(x = '', 
       y = '', 
       title = 'Mine 8: Precipitation Events by Duration') + 
  scale_y_continuous(expand = c(0,0), limits = c(0,400)) + #CAN DO THIS FOR ABOVE WEATHER TO MAKE THEM LOOK NICER
  scale_x_datetime(expand = c(0, 0)) +
  theme_bw() + 
  theme(axis.title.y = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.y = element_blank())

PD8

```

```{r merge in rockfall}

m8Falls <- valData |> 
  subset(select = c(date, timeOfInitiation)) |> 
  mutate(date = gsub("24", "2022", date)) |>
  separate(timeOfInitiation, into = c('h', 'm', 's'), sep = ':') |>
  mutate(
    # Add leading zero if hours, minutes, or seconds have only one digit
    h = sprintf("%02d", as.numeric(h)),
    m = sprintf("%02d", as.numeric(m)),
    s = sprintf("%02d", as.numeric(s))
  ) |> 
  unite(timeOfInitiation, h, m, s, sep = ":")

m8Falls$datetime <- as.POSIXct(mdy_hms(paste(m8Falls$date, m8Falls$timeOfInitiation, sep = " "))) 

M8Rockfalls <- m8Falls |> 
  arrange(datetime) |> 
  subset(select = c(datetime))


#create daily count
rockfallsDailyCount <- M8Rockfalls |>
  mutate(rockfall = 1, date = as_date(datetime)) |>
  group_by(date) |>
  summarize(rockfall = sum(rockfall), avg_time = mean(datetime)) |>
  mutate(cumuRockfall = cumsum(rockfall))

#plot daily rockfall
RF8 <- ggplot(rockfallsDailyCount) + 
  geom_point(aes(as.POSIXct(avg_time), rockfall), color = 'red') +
  geom_line(aes(as.POSIXct(avg_time), rockfall)) +
  # geom_point(aes(as.POSIXct (date), cumuRockfall), color = 'red') +
  # geom_line(aes(as.POSIXct (date), cumuRockfall)) +
  labs(title = 'Daily Sum of Rockfall Events', 
       y = 'Count of Rockfall Events') + 
  scale_y_continuous(limits = c(0,50)) +
  scale_x_datetime(expand = c(0, 0)) +
  theme_bw() + 
  theme(
    axis.title.x = element_blank(), 
    axis.text.y = element_text(size = 14), 
    axis.title.y = element_text(size = 14), 
    axis.text.x = element_text(size = 14), 
    plot.title = element_text(size = 18)
  )

ggsave(here("figures/mine8RockfallValidatedTimeSeries.png"), plot=RF8, width=7, height=5)

RF8
#---------------------------------------
#add in the rockfall to the weather data
#---------------------------------------

m8WeatherHour <- subset(mine8Weather, select = -c(time,cumuRain))

m8Falls$hour_only <- format(m8Falls$datetime, "%Y-%m-%d %H")

m8WeatherHour_wRF <- m8WeatherHour |>
  mutate('rockfall' = ifelse(format(datetime, "%Y-%m-%d %H") %in% m8Falls$hour_only, 1, 0))



#plot with hourly rockfall 



# Create daily count and unique hour count
rockfallsDailyCount <- M8Rockfalls |>
  mutate(rockfall = 1, 
         date = as_date(datetime), 
         hour = hour(datetime)) |>
  group_by(date) |>
  summarize(
    rockfall = sum(rockfall),  # Total rockfalls per day
    unique_hours = n_distinct(hour),  # Count of unique hours with rockfalls
    avg_time = mean(datetime)  # Average timestamp for plotting
  ) |>
  mutate(cumuRockfall = cumsum(rockfall))

# Plot daily rockfall with unique hour count
RF8 <- ggplot(rockfallsDailyCount, aes(x = as.POSIXct(avg_time))) + 
  geom_point(aes(y = rockfall, color = "Discrete Rockfalls")) +
  geom_line(aes(y = rockfall, color = "Discrete Rockfalls")) +
  geom_point(aes(y = unique_hours, color = "Rockfall Hours")) +
  geom_line(aes(y = unique_hours, color = "Rockfall Hours")) +
  labs(title = 'Daily Rockfall Events and Hours of Initiation', 
       y = 'Discrete Count',
       color = "Legend") +  # Legend title
  scale_y_continuous(
    limits = c(0, 40), 
    sec.axis = sec_axis(~ . * (24 / 40), name = "Hours with Rockfall")  # Rescale to max 24 hours
  ) +   scale_x_datetime(expand = c(0, 0)) +
  scale_color_manual(values = c("Discrete Rockfalls" = "red", "Rockfall Hours" = "blue")) +  # Custom colors
  theme_bw() + 
  theme(
    axis.title.x = element_blank(), 
    axis.text.y = element_text(size = 14), 
    axis.title.y = element_text(size = 14), 
    axis.text.x = element_text(size = 14), 
    plot.title = element_text(size = 18),
    legend.position = "bottom",
    legend.title = element_blank()
  )

RF8


ggsave(here("figures/mine8RockfallValidatedTimeSeries.png"), plot=RF8, width=7, height=5)


#-----------------------
#save data as a R object
#-----------------------

saveRDS(M8Rockfalls, here("mine8RockfallsValidatedMinute.rds"))


saveRDS(m8WeatherHour_wRF, here("mine8FinalDataValidated.rds"))

```



